### ISSUE TITLE
Add "Large Language Models Are State-of-the-Art Evaluators of Code Generation"

### ISSUE THREAD

**Issue by terryyz** [NTDXYG/CodeMetrics-Papers#1]
Hi Guang,

Please note my recent paper [Large Language Models Are State-of-the-Art Evaluators of Code Generation](https://arxiv.org/abs/2304.14317) on this topic :)

Cheers

**Comment by NTDXYG** [comment]
okay, I think it is an excellent paper. 

I have recently been doing some research on the issue of evaluation metrics for code synthesis and the security of backdoor attacks in code synthesis models.

I'm reading your latest research paper on these topics, can I ask for some advice on confusion or a relevant research collaboration?
